/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.16.5.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export type ExecuteMsg = {
  increment: {};
} | {
  reset: {
    count: number;
  };
} | {
  add_recipient_to_queue: {
    caller: string;
    recipient: string;
  };
};
export interface InstantiateMsg {
  count: number;
}
export type QueryMsg = {
  get_count: {};
} | {
  get_caller_recipient: {};
};
export interface GetCallerRecipientResponse {
  callerRecipient: [string, string][];
}
export interface GetCountResponse {
  count: number;
}